Repository message-exp/nori-server, pull requests merged in 2025-02, with the labels that each got.

#9 Ci: add submodule checkout validation in GitHub Actions
  .github/workflows/submodule.yml
Labels: help wanted

#11 feat/api structure and script revise
  .devcontainer/docker-compose.yml
  scripts/generate.py
  src/api/message/message_service.py
  src/api/room/room_service.py
  src/api/server.py
  src/api/user/user_service.py
  src/main.py
Labels: enhancement

#12 docs(readme): Update README.md
  README.md
Labels: documentation

#17 Fix: user_id to id
  src/api/room/room_service.py
  tests/api/room/test_room_service.py
Labels: bug

#8 feat: MES-33 token authentication handler
  .coveragerc
  .env.sample
  .vscode/settings.json
  poetry.lock
  pyproject.toml
  pytest.ini
  src/api/message/message_service.py
  src/api/room/room_service.py
  src/api/user/user_service.py
  src/db.py
  src/utils/token_helper.py
  tests/api/room/test_room_service.py
Labels: enhancement

#19 feat/invite to room endpoint
  src/api/room/room_service.py
  src/migrate/versions/00be3b7f9445_init_users_rooms_room_members_and_.py
  src/migrate/versions/a6b6a2750ff6_init_users_rooms_room_members_and_.py
  src/model.py
  src/repositories/__init__.py
  src/repositories/room_member_repository.py
  src/repositories/room_repostitory.py
  src/repositories/user_repository.py
  tests/api/room/test_room_service.py
Labels: bug, enhancement

#20 Erer/feat/join room and get room endpoint
  src/api/room/room_service.py
  src/repositories/room_repostitory.py
  tests/api/room/test_room_service.py
Labels: enhancement

#14 feat: MES-46 get user endpoint implementation
  src/api/user/user_service.py
  src/repositories/user_repository.py
  tests/api/user/test_get_user.py
Labels: enhancement

#18 feat: MES-47 get user room list endpoint implementation
  src/api/user/user_service.py
  src/repositories/room_member_repository.py
  tests/api/user/test_get_user_room_list.py
Labels: enhancement

#22 Fix: regenerate migrate script
  src/migrate/versions/a6b6a2750ff6_init_users_rooms_room_members_and_.py
  src/migrate/versions/a961154dab00_init_users_rooms_room_members_and_.py
Labels: bug

#24 Feat: add RefreshToken model with foreign key to Users
  src/migrate/versions/33e035c76f35_init_users_rooms_room_members_messages_.py
  src/model.py
Labels: enhancement

#26 feat: MES-34 log in endpoint implementation
  .vscode/settings.json
  src/api/user/user_service.py
  src/repositories/__init__.py
  src/repositories/refresh_token_repository.py
  src/repositories/room_repository.py
  src/repositories/user_repository.py
  src/utils/token_helper.py
  src/utils/validate_format_helper.py
  tests/api/room/test_room_service.py
  tests/api/user/test_get_user.py
  tests/api/user/test_get_user_room_list.py
  tests/api/user/test_login.py
  tests/utils/test_is_valid_email.py
Labels: enhancement

#27 feat: MES-36 sign up endpoint implementation
  src/api/user/user_service.py
  src/repositories/user_repository.py
  tests/api/messages/test_get_messages.py
  tests/api/messages/test_send_messages.py
  tests/api/user/test_signup.py
Labels: enhancement

#28 fix: src import error
  src/api/message/message_service.py
Labels: bug

#29 Chore: add envoy setting
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/envoy.yml
  .env.sample
  Dockerfile
Labels: enhancement

#32 Erer/hot fix/update model and argument error
  .devcontainer/Dockerfile
  src/api/user/user_service.py
  src/migrate/versions/5628859f20d3_init_users_rooms_room_members_messages_.py
  src/model.py
Labels: bug

#30 feat: logging interceptor
  src/api/logging_interceptor.py
  src/api/server.py
Labels: enhancement

#35 feat/docker config
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  Dockerfile
  docker-compose.yml
  envoy/envoy.yml
Labels: enhancement

#36 Feat: add build script
  docker-compose.yml
  scripts/build.sh
Labels: enhancement
