Repository message-exp/nori-server, pull requests merged in 2025-03, with the labels that each got.

#39 Fix: update docker-compose volume path for nori-server
  .devcontainer/docker-compose.yml
Labels: bug

#41 fix: architecture error on mac
  .devcontainer/Dockerfile
Labels: bug

#46 Fix/refresh token return type error
  src/api/user/user_access_service.py
  src/repositories/message_repository.py
Labels: bug

#47 Fix:unuse parameter in RefreshToken endpoint
  src/api/user/user_access_service.py
Labels: bug

#42 chore: environment and docs update for production
  .env.devcontainer
  .env.stage
  .github/workflows/pytest.yml
  README.md
  docker-compose.yml
Labels: documentation, enhancement

#45 Fix: handle empty avatar URL
  src/api/room/room_member_service.py
  src/api/user/user_network_service.py
Labels: bug

#48 Refactor/pytests path refactor
  .coveragerc
  src/api/user/user_access_service.py
  src/api/user/user_network_service.py
  tests/api/messages/test_get_history_messages.py
  tests/api/messages/test_get_latest_messages.py
  tests/api/messages/test_send_messages.py
  tests/api/room/room_general/test_create_room.py
  tests/api/room/room_general/test_get_room.py
  tests/api/room/room_general/test_get_room_basic_info.py
  tests/api/room/room_member/test_invite_to_room_test.py
  tests/api/room/room_member/test_join_room.py
  tests/api/room/test_room_service.py
  tests/api/user/test_login.py
  tests/api/user/test_signup.py
  tests/api/user/user_access/test_login.py
  tests/api/user/user_account/test_get_user.py
  tests/api/user/user_account/test_signup.py
  tests/api/user/user_network/test_get_user_room_list.py
  tests/conftest.py
Labels: enhancement
